const RiderSupport={
session:null,tickets:[],selected:'',
esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));},
async init(){this.session=JSON.parse(localStorage.getItem('desimall_rider_session')||'null');if(!this.session?.token){location.href='login.html';return;}riderName.textContent=this.session?.rider?.RiderName||this.session?.profile?.full_name||'Rider';logoutBtn.onclick=()=>{localStorage.removeItem('desimall_rider_session');location.href='login.html'};refreshRiderSupport.onclick=()=>this.load();newRiderTicket.onclick=()=>riderTicketModal.classList.add('show');closeRiderTicket.onclick=()=>riderTicketModal.classList.remove('show');riderTicketForm.onsubmit=e=>{e.preventDefault();this.create()};await this.load();},
async load(){const r=await DesiMallAPI.getRiderSupport(this.session.token);if(!r.success){riderTicketList.innerHTML=`<div class="support-empty">${this.esc(r.message||'Could not load support.')}</div>`;return;}this.tickets=r.tickets||[];this.render();if(this.selected&&this.tickets.some(x=>x.TicketID===this.selected))this.open(this.selected,true);},
render(){riderTicketList.innerHTML=this.tickets.length?this.tickets.map(t=>`<article class="ticket-item ${this.selected===t.TicketID?'active':''}" onclick="RiderSupport.open('${this.esc(t.TicketID)}')"><div class="ticket-row"><strong>${this.esc(t.TicketID)}</strong><span>${this.esc(t.Status)}</span></div><h3>${this.esc(t.Subject)}</h3><div class="ticket-meta">${this.esc(t.Category)}</div></article>`).join(''):'<div class="support-empty"><strong>No rider support tickets</strong></div>';},
async open(id,skip=false){this.selected=id;this.render();const t=this.tickets.find(x=>x.TicketID===id);if(!t)return;riderTicketDetail.className='';riderTicketDetail.innerHTML=`<h2>${this.esc(t.Subject)}</h2><div class="ticket-description">${this.esc(t.Description)}</div><div class="support-chat">${(t.Replies||[]).map(r=>`<div class="chat-message ${r.SenderType==='Rider'?'seller':'admin'}"><strong>${this.esc(r.SenderName||r.SenderType)}</strong><div>${this.esc(r.Message)}</div></div>`).join('')}</div>${t.Status==='Closed'?'':`<form onsubmit="event.preventDefault();RiderSupport.reply()"><div class="chat-tools"><textarea id="riderReply" required></textarea><button class="r-btn">Send</button></div></form>`}`;if(!skip&&t.LastReplyBy==='Admin'&&!t.RequesterSeenAt){await DesiMallAPI.markRiderSupportSeen({Token:this.session.token,TicketID:id});t.RequesterSeenAt=new Date().toISOString();}},
async create(){const r=await DesiMallAPI.createRiderSupportTicket({Token:this.session.token,Category:riderCategory.value,Priority:riderPriority.value,Subject:riderSubject.value,Description:riderDescription.value});if(!r.success){alert(r.message||'Ticket failed.');return;}riderTicketForm.reset();riderTicketModal.classList.remove('show');this.selected=r.ticketId;await this.load();},
async reply(){const r=await DesiMallAPI.riderSupportReply({Token:this.session.token,TicketID:this.selected,Message:riderReply.value});if(!r.success){alert(r.message||'Reply failed.');return;}await this.load();}
};document.addEventListener('DOMContentLoaded',()=>RiderSupport.init());