const SellerSupport={
session:null,tickets:[],selectedId:'',attachment:null,pollTimer:null,lastUpdated:'',
esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));},
date(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('hi-IN',{dateStyle:'medium',timeStyle:'short'});},
toast(m){panelToast.textContent=m;panelToast.classList.add('show');setTimeout(()=>panelToast.classList.remove('show'),2500);},
async init(){this.session=JSON.parse(localStorage.getItem('desimall_seller_session')||'null');if(!this.session?.token){location.href='login.html';return;}newTicketBtn.onclick=()=>ticketModal.classList.add('show');closeTicketModal.onclick=()=>ticketModal.classList.remove('show');ticketModal.onclick=e=>{if(e.target===ticketModal)ticketModal.classList.remove('show')};refreshSupport.onclick=()=>this.load();ticketFilter.onchange=()=>this.renderList();ticketForm.onsubmit=e=>{e.preventDefault();this.create()};ticketAttachment.onchange=e=>this.pick(e.target.files[0]);await this.load();
this.startPolling();
document.addEventListener('visibilitychange',()=>{if(document.hidden)this.stopPolling();else{this.startPolling();this.load(true);}});
},
async load(silent=false){
const r=await DesiMallAPI.getSellerSupport(this.session.token);
if(!r.success){sellerSupportLive.innerHTML='<i class="fa-solid fa-circle"></i> ऑफलाइन';if(!silent)this.toast(r.message||'मदद टिकट लोड नहीं हुए।');return;}
sellerSupportLive.innerHTML='<i class="fa-solid fa-circle"></i> लाइव';
this.tickets=r.tickets||[];const s=r.stats||{};
supportTotal.textContent=s.total||0;supportUnread.textContent=s.unread||0;supportUrgent.textContent=s.urgent||0;supportResolved.textContent=s.resolved||0;
this.renderList();if(this.selectedId)this.open(this.selectedId,true);
},
renderList(){const f=ticketFilter.value,rows=this.tickets.filter(t=>!f||t.Status===f);ticketList.innerHTML=rows.length?rows.map(t=>`<article class="ticket-item ${this.selectedId===t.TicketID?'active':''} ${t.LastReplyBy==='Admin'&&!t.RequesterSeenAt?'unread':''}" onclick="SellerSupport.open('${this.esc(t.TicketID)}')"><div class="ticket-row"><strong>${this.esc(t.TicketID)}</strong><span class="ticket-badge status-${String(t.Status).replaceAll(' ','-')}">${this.esc(t.Status)}</span></div><h3>${this.esc(t.Subject)}</h3><div class="ticket-meta"><span>${this.esc(t.Category)}</span><span class="ticket-badge priority-${this.esc(t.Priority)}">${this.esc(t.Priority)}</span><span>${this.date(t.UpdatedAt||t.CreatedAt)}</span></div></article>`).join(''):'<div class="support-empty"><i class="fa-solid fa-ticket"></i><strong>अभी कोई टिकट नहीं</strong><span>समस्या हो तो “नया टिकट” दबाएँ।</span></div>';},
async open(id,skipSeen=false){
this.selectedId=id;this.renderList();const t=this.tickets.find(x=>x.TicketID===id);if(!t)return;
ticketEmpty.hidden=true;ticketDetail.hidden=false;const replies=t.Replies||[];
ticketDetail.innerHTML=`<div class="ticket-detail-head"><div><h2>${this.esc(t.Subject)}</h2><div class="ticket-meta"><strong>${this.esc(t.TicketID)}</strong><span>${this.esc(t.Category)}</span><span class="ticket-badge priority-${this.esc(t.Priority)}">${this.esc(t.Priority)}</span></div></div><span class="ticket-badge status-${String(t.Status).replaceAll(' ','-')}">${this.esc(t.Status)}</span></div><div class="ticket-description">${this.esc(t.Description)}</div><div class="support-chat" id="supportChat">${replies.map((r,idx)=>`<div class="chat-message ${r.SenderType==='Seller'?'seller':'admin'}"><strong>${this.esc(r.SenderName||r.SenderType)}</strong><div>${this.esc(r.Message)}</div>${r.AttachmentURL?`<a class="attachment-link" href="${this.esc(r.AttachmentURL)}" target="_blank"><i class="fa-solid fa-paperclip"></i>${this.esc(r.AttachmentName||'Attachment')}</a>`:''}<small>${this.date(r.CreatedAt)}</small>${r.SenderType==='Seller'&&idx===replies.length-1?'<div class="seen-line">'+(t.AdminSeenAt?'Seen':'Sent')+'</div>':''}</div>`).join('')}</div><div class="typing-indicator" id="sellerTypingIndicator">DesiMall support is typing...</div>${t.Status==='Closed'?'<div class="hisab-note">This ticket is closed.</div>':`<form onsubmit="event.preventDefault();SellerSupport.reply()"><div class="chat-tools"><button type="button" onclick="SellerSupport.toggleEmoji()" title="Emoji"><i class="fa-regular fa-face-smile"></i></button><textarea id="supportReplyText" placeholder="Write a reply..." required></textarea><button class="btn btn-primary" title="भेजें"><i class="fa-solid fa-paper-plane"></i></button></div><div class="emoji-row" id="sellerEmojiRow">${['🙂','🙏','👍','✅','📦','💰','⚠️','धन्यवाद'].map(e=>`<button type="button" onclick="SellerSupport.addEmoji('${e}')">${e}</button>`).join('')}</div></form>`}`;
requestAnimationFrame(()=>{const box=document.getElementById('supportChat');if(box)box.scrollTop=box.scrollHeight;});
if(!skipSeen&&t.LastReplyBy==='Admin'&&!t.RequesterSeenAt){await DesiMallAPI.markSellerSupportSeen({Token:this.session.token,TicketID:id});t.RequesterSeenAt=new Date().toISOString();supportUnread.textContent=Math.max(0,Number(supportUnread.textContent||0)-1);this.renderList();}
},
toggleEmoji(){document.getElementById('sellerEmojiRow')?.classList.toggle('show');},
addEmoji(e){const el=document.getElementById('supportReplyText');if(el){el.value+=(el.value?' ':'')+e;el.focus();}},
startPolling(){this.stopPolling();this.pollTimer=setInterval(()=>{if(!document.hidden)this.load(true);},12000);},
stopPolling(){if(this.pollTimer){clearInterval(this.pollTimer);this.pollTimer=null;}},
async pick(file){this.attachment=null;attachmentPreview.innerHTML='';if(!file)return;if(file.size>5*1024*1024){this.toast('फाइल 5 MB से छोटी रखें।');ticketAttachment.value='';return;}const reader=new FileReader();reader.onload=()=>{this.attachment={FileName:file.name,MimeType:file.type,Base64Data:reader.result};attachmentPreview.innerHTML=`<img src="${reader.result}" alt="preview">`};reader.readAsDataURL(file);},
async uploadAttachment(){if(!this.attachment)return {success:true};return DesiMallAPI.uploadProductImage({...this.attachment,Token:this.session.token});},
async create(){submitTicketBtn.disabled=true;submitTicketBtn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Sending...';const up=await this.uploadAttachment();if(!up.success){submitTicketBtn.disabled=false;submitTicketBtn.innerHTML='Submit Ticket';this.toast(up.message||'Screenshot upload failed.');return;}const r=await DesiMallAPI.createSellerSupportTicket({Token:this.session.token,Category:ticketCategory.value,Priority:ticketPriority.value,Subject:ticketSubject.value,Description:ticketDescription.value,AttachmentURL:up.imageUrl||'',AttachmentName:up.fileName||''});submitTicketBtn.disabled=false;submitTicketBtn.innerHTML='<i class="fa-solid fa-paper-plane"></i> Submit Ticket';if(!r.success){this.toast(r.message||'Ticket could not be created.');return;}ticketForm.reset();attachmentPreview.innerHTML='';this.attachment=null;ticketModal.classList.remove('show');this.selectedId=r.ticketId;this.toast(`${r.ticketId} created.`);await this.load();
this.startPolling();
document.addEventListener('visibilitychange',()=>{if(document.hidden)this.stopPolling();else{this.startPolling();this.load(true);}});
},
async reply(){const el=document.getElementById('supportReplyText'),message=el?.value.trim();if(!message)return;const r=await DesiMallAPI.sellerSupportReply({Token:this.session.token,TicketID:this.selectedId,Message:message});if(!r.success){this.toast(r.message||'Reply could not be sent.');return;}this.toast(r.message);await this.load();}
};document.addEventListener('DOMContentLoaded',()=>SellerSupport.init());