const AdminLive={
  token(){
    try{
      return JSON.parse(localStorage.getItem('desimall_admin_session')||'null')?.token||'';
    }catch(_){return '';}
  },
  page:document.body.dataset.page||'dashboard', data:[], money:n=>`₹${Number(n||0).toLocaleString('en-IN')}`,
  esc:v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),
  statusClass:v=>String(v||'').toLowerCase().replace(/\s+/g,'-'),
  toast(m){const e=document.getElementById('adminToast');if(!e)return;e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)},
  async init(){this.bindCommon(); if(this.page==='dashboard')await this.dashboard();if(this.page==='orders')await this.orders();if(this.page==='inventory')await this.inventory();if(this.page==='sellers')await this.sellers();if(this.page==='riders')await this.riders();},
  bindCommon(){document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('show'));},
  async dashboard(){const [r,f]=await Promise.all([DesiMallAPI.getAdminDashboard(),DesiMallAPI.getFinanceDashboard()]);if(!r.success){this.toast(r.message||'Dashboard load failed');return}const s=r.stats||{},fs=f.success?(f.stats||{}):{};this.text('statRevenue',this.money(fs.gmv!==undefined?fs.gmv:s.revenue));this.text('statGrossIncome',this.money(fs.grossIncome||0));this.text('statNetProfit',this.money(fs.netProfit||0));this.text('statPendingSettlement',this.money(fs.pendingSettlement||0));this.text('statCODCash',this.money(fs.cashWithRiders||0));this.text('statOrders',s.orders||0);this.text('statCustomers',s.customers||0);this.text('statProducts',s.products||0);this.renderRecent(r.recentOrders||[]);this.renderChart(r.monthlyRevenue||{});this.renderLow(r.lowStock||[])}, 
  text(id,v){const e=document.getElementById(id);if(e)e.textContent=v},
  renderRecent(rows){const b=document.getElementById('recentBody');b.innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${this.esc(o.OrderID)}</strong></td><td>${this.esc(o.CustomerName||'Customer')}<div class="muted">${this.esc(o.CustomerMobile||'')}</div></td><td>${this.money(o.TotalAmount)}</td><td><span class="badge ${this.statusClass(o.Status)}">${this.esc(o.Status)}</span></td><td>${this.date(o.OrderDate)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No orders found.</td></tr>'},
  renderChart(obj){const e=document.getElementById('revenueChart'),now=new Date(),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;months.push({k,label:d.toLocaleString('en',{month:'short'}),v:Number(obj[k]||0)})}const max=Math.max(1,...months.map(x=>x.v));e.innerHTML=months.map(x=>`<div class="chart-col" title="${this.money(x.v)}"><div class="chart-bar" style="height:${Math.max(3,x.v/max*90)}%"></div><small>${x.label}</small></div>`).join('')},
  renderLow(rows){const e=document.getElementById('lowStock');e.innerHTML=rows.length?rows.map(p=>`<div style="display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid var(--a-border)"><div><strong>${this.esc(p.ProductName||p.Name)}</strong><div class="muted">${this.esc(p.SKU||p.Category||'')}</div></div><span class="badge ${Number(p.Stock)<=0?'suspended':'pending'}">${Number(p.Stock||0)} left</span></div>`).join(''):'<div class="empty">No low-stock alerts.</div>'},
  async orders(){document.getElementById('orderSearch').oninput=()=>this.filterOrders();document.getElementById('orderStatus').onchange=()=>this.filterOrders();try{const c=JSON.parse(localStorage.getItem('dm_admin_orders_fast')||'null');if(c&&Array.isArray(c.orders)){this.data=c.orders;this.filterOrders();}}catch(_){}const r=await DesiMallAPI.getAdminOrders({},this.token());this.data=r.orders||[];try{localStorage.setItem('dm_admin_orders_fast',JSON.stringify({orders:this.data,time:Date.now()}));}catch(_){}this.filterOrders()},
  filterOrders(){const q=document.getElementById('orderSearch').value.toLowerCase(),s=document.getElementById('orderStatus').value.toLowerCase();let rows=this.data.filter(o=>(!q||[o.OrderID,o.CustomerName,o.CustomerMobile,o.ProductName,o.ShopName].some(v=>String(v||'').toLowerCase().includes(q)))&&(!s||s==='all'||String(o.Status||'').toLowerCase()===s));document.getElementById('ordersBody').innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${this.esc(o.OrderID)}</strong><div class="muted">${this.date(o.OrderDate)}</div></td><td>${this.esc(o.CustomerName||'')}<div class="muted">${this.esc(o.CustomerMobile||'')}</div></td><td>${this.esc(o.ProductName||'')} × ${Number(o.Quantity||1)}</td><td>${this.esc(o.ShopName||o.SellerName||o.SellerID||'')}</td><td>${this.money(o.TotalAmount)}</td><td><span class="badge ${this.statusClass(o.Status)}">${this.esc(o.Status)}</span></td><td>${this.esc(o.PaymentMethod||'')}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">No orders found.</td></tr>';this.text('orderCount',`${rows.length} records`)},
  async inventory(){document.getElementById('inventorySearch').oninput=()=>this.filterInventory();document.getElementById('inventoryFilter').onchange=()=>this.filterInventory();
try{const c=JSON.parse(localStorage.getItem('dm_admin_inventory_fast')||'null');if(c&&Array.isArray(c.products)){this.data=c.products;const s=c.summary||{};this.text('invProducts',s.products||0);this.text('invStock',s.totalStock||0);this.text('invReserved',s.reserved||0);this.text('invValue',this.money(s.value));this.filterInventory();}}catch(_){}
const r=await DesiMallAPI.getAdminInventory({},this.token());this.data=r.products||[];const s=r.summary||{};try{localStorage.setItem('dm_admin_inventory_fast',JSON.stringify({products:this.data,summary:s,time:Date.now()}));}catch(_){};this.text('invProducts',s.products||0);this.text('invStock',s.totalStock||0);this.text('invReserved',s.reserved||0);this.text('invValue',this.money(s.value));this.filterInventory()},
  filterInventory(){const q=document.getElementById('inventorySearch').value.toLowerCase(),f=document.getElementById('inventoryFilter').value;let rows=this.data.filter(p=>(!q||[p.ProductName,p.SKU,p.Category,p.ShopName,p.SellerName,p.ProductID].some(v=>String(v||'').toLowerCase().includes(q)))&&(f==='all'||(f==='low'&&Number(p.Stock)>0&&Number(p.Stock)<=5)||(f==='out'&&Number(p.Stock)<=0)));document.getElementById('inventoryBody').innerHTML=rows.length?rows.map(p=>`<tr><td><div class="entity"><img class="product-img" src="${this.esc(p.ImageURL||p.Image||'')}" onerror="this.style.visibility='hidden'"><div><strong>${this.esc(p.ProductName||'Product')}</strong><div class="muted">${this.esc(p.SKU||p.ProductID||'')}</div></div></div></td><td>${this.esc(p.ShopName||p.SellerName||p.SellerID||'')}</td><td>${this.esc(p.Category||'')}</td><td>${Number(p.Stock||0)}</td><td>${Number(p.ReservedStock||0)}</td><td>${Number(p.SoldQty||0)}</td><td>${this.money(p.InventoryValue)}</td><td><span class="badge ${Number(p.Stock)<=0?'suspended':Number(p.Stock)<=5?'pending':'active'}">${Number(p.Stock)<=0?'Out':Number(p.Stock)<=5?'Low':'Healthy'}</span></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No products found.</td></tr>'},
  async sellers(){const r=await DesiMallAPI.getAdminSellers(this.token());this.data=r.sellers||[];this.renderSellerStats();document.getElementById('sellerSearch').oninput=()=>this.renderSellers();document.getElementById('sellerStatus').onchange=()=>this.renderSellers();this.renderSellers()},
  renderSellerStats(){const all=this.data;this.text('sellerTotal',all.length);this.text('sellerActive',all.filter(x=>String(x.Status).toLowerCase()==='active').length);this.text('sellerPending',all.filter(x=>String(x.Status).toLowerCase()==='pending').length);this.text('sellerSubmitted',all.filter(x=>String(x.KYCStatus).toLowerCase()==='submitted').length);this.text('sellerSuspended',all.filter(x=>String(x.Status).toLowerCase()==='suspended').length)},
  renderSellers(){const q=document.getElementById('sellerSearch').value.toLowerCase(),st=document.getElementById('sellerStatus').value.toLowerCase();const rows=this.data.filter(s=>(!q||[s.SellerName,s.ShopName,s.Mobile,s.Email,s.SellerID].some(v=>String(v||'').toLowerCase().includes(q)))&&(!st||st==='all'||String(s.Status).toLowerCase()===st));document.getElementById('sellersBody').innerHTML=rows.length?rows.map(s=>`<tr><td><div class="entity">${s.ProfileImage?`<img class="avatar" src="${this.esc(s.ProfileImage)}">`:`<span class="avatar">${this.initials(s.SellerName)}</span>`}<div><strong>${this.esc(s.SellerName)}</strong><div class="muted">${this.esc(s.ShopName)}</div></div></div></td><td>${this.esc(s.Mobile)}<div class="muted">${this.esc(s.Email)}</div></td><td><span class="badge ${this.statusClass(s.KYCStatus)}">${this.esc(s.KYCStatus)}</span></td><td>${s.ProductCount||0}</td><td>${s.OrderCount||0}</td><td>${this.money(s.Revenue)}</td><td><span class="badge ${this.statusClass(s.Status)}">${this.esc(s.Status)}</span></td><td><button class="a-btn small" onclick="AdminLive.openSeller('${this.esc(s.SellerID)}')">View / Manage</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No sellers found.</td></tr>'},
  openSeller(id){const s=this.data.find(x=>String(x.SellerID)===String(id));if(!s)return;document.getElementById('sellerModal').classList.add('show');const doc=(label,url)=>url?`<a class="a-btn small" href="${this.esc(url)}" target="_blank" rel="noopener"><i class="fa-solid fa-file-arrow-up"></i> ${label}</a>`:`<span class="muted">${label}: not uploaded</span>`;document.getElementById('sellerForm').innerHTML=`<input type="hidden" name="SellerID" value="${this.esc(s.SellerID)}"><input type="hidden" name="AdminName" value="Admin"><label>Seller status<select name="Status"><option>${this.esc(s.Status)}</option>${['Pending','Active','Rejected','Suspended','Inactive'].filter(x=>x!==s.Status).map(x=>`<option>${x}</option>`).join('')}</select></label><label>KYC status<select name="KYCStatus"><option>${this.esc(s.KYCStatus)}</option>${['Not Submitted','Submitted','Approved','Rejected'].filter(x=>x!==s.KYCStatus).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Commission %<input name="CommissionPercent" type="number" min="0" max="100" value="${Number(s.CommissionPercent||10)}"></label><label>Business type<input value="${this.esc(s.BusinessType)}" readonly></label><label>GSTIN<input name="GSTIN" value="${this.esc(s.GSTIN)}"></label><label>PAN<input name="PAN" value="${this.esc(s.PAN)}"></label><label>Aadhaar<input name="Aadhaar" value="${this.esc(s.Aadhaar)}"></label><label>Bank name<input name="BankName" value="${this.esc(s.BankName)}"></label><label>Account number<input name="AccountNumber" value="${this.esc(s.AccountNumber)}"></label><label>IFSC<input name="IFSC" value="${this.esc(s.IFSC)}"></label><label>UPI ID<input name="UPIID" value="${this.esc(s.UPIID)}"></label><div class="full kyc-docs"><strong>KYC documents</strong><div class="doc-actions">${doc('Aadhaar',s.AadhaarDocumentURL)} ${doc('PAN',s.PANDocumentURL)} ${doc('GST',s.GSTDocumentURL)} ${doc('Bank proof',s.BankDocumentURL)}</div></div><label class="full">KYC review notes<textarea name="KYCNotes">${this.esc(s.KYCNotes)}</textarea></label><label class="full">Suspend/reject reason<textarea name="SuspendedReason">${this.esc(s.SuspendedReason)}</textarea></label><div class="full muted">Submitted: ${this.esc(s.KYCSubmittedAt||'—')}<br>Reviewed: ${this.esc(s.KYCReviewedAt||'—')} by ${this.esc(s.KYCReviewedBy||'—')}</div>`;document.getElementById('sellerModalTitle').textContent=`${s.SellerName} · ${s.ShopName}`},
  async saveSeller(){const f=new FormData(document.getElementById('sellerForm')),data=Object.fromEntries(f.entries());if(data.KYCStatus==='Approved')data.Status='Active';if(data.KYCStatus==='Rejected'&&!String(data.KYCNotes||'').trim())return this.toast('KYC rejection note required.');const r=await DesiMallAPI.updateAdminSeller(data);this.toast(r.message||'Updated');if(r.success){document.getElementById('sellerModal').classList.remove('show');await this.sellers()}},

  async riders(){const r=await DesiMallAPI.getAdminRiders(this.token());this.data=r.riders||[];this.renderRiderStats();document.getElementById('riderSearch').oninput=()=>this.renderRiders();document.getElementById('riderStatus').onchange=()=>this.renderRiders();this.renderRiders()},
  renderRiderStats(){const all=this.data;this.text('riderTotal',all.length);this.text('riderActive',all.filter(x=>String(x.Status).toLowerCase()==='active').length);this.text('riderOnline',all.filter(x=>String(x.Availability).toLowerCase()==='online').length);this.text('riderSuspended',all.filter(x=>String(x.Status).toLowerCase()==='suspended').length)},
  renderRiders(){const q=document.getElementById('riderSearch').value.toLowerCase(),st=document.getElementById('riderStatus').value.toLowerCase();const rows=this.data.filter(r=>(!q||[r.RiderName,r.Mobile,r.VehicleNumber,r.RiderID].some(v=>String(v||'').toLowerCase().includes(q)))&&(!st||st==='all'||String(r.Status).toLowerCase()===st));document.getElementById('ridersBody').innerHTML=rows.length?rows.map(r=>`<tr><td><div class="entity">${r.ProfileImage?`<img class="avatar" src="${this.esc(r.ProfileImage)}">`:`<span class="avatar">${this.initials(r.RiderName)}</span>`}<div><strong>${this.esc(r.RiderName)}</strong><div class="muted">${this.esc(r.Mobile)}</div></div></div></td><td>${this.esc(r.VehicleType)}<div class="muted">${this.esc(r.VehicleNumber)}</div></td><td>${this.esc(r.ServicePincode)}</td><td><span class="badge ${this.statusClass(r.Availability)}">${this.esc(r.Availability)}</span></td><td><span class="badge ${this.statusClass(r.KYCStatus)}">${this.esc(r.KYCStatus)}</span></td><td>${r.ActiveOrders||0} / ${r.DeliveredOrders||0}</td><td><span class="badge ${this.statusClass(r.Status)}">${this.esc(r.Status)}</span></td><td><button class="a-btn small" onclick="AdminLive.openRider('${this.esc(r.RiderID)}')">View / Manage</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No riders found.</td></tr>'},
  openRider(id){const r=this.data.find(x=>String(x.RiderID)===String(id));if(!r)return;document.getElementById('riderModal').classList.add('show');document.getElementById('riderForm').innerHTML=`<input type="hidden" name="RiderID" value="${this.esc(r.RiderID)}"><label>Rider status<select name="Status"><option>${this.esc(r.Status)}</option>${['Pending','Active','Rejected','Suspended','Inactive'].filter(x=>x!==r.Status).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Availability<select name="Availability"><option>${this.esc(r.Availability)}</option>${['Offline','Online','Busy'].filter(x=>x!==r.Availability).map(x=>`<option>${x}</option>`).join('')}</select></label><label>KYC status<select name="KYCStatus"><option>${this.esc(r.KYCStatus)}</option>${['Pending','Approved','Rejected'].filter(x=>x!==r.KYCStatus).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Aadhaar<input name="Aadhaar" value="${this.esc(r.Aadhaar)}"></label><label>Driving licence<input name="DrivingLicence" value="${this.esc(r.DrivingLicence)}"></label><label>RC number<input name="RCNumber" value="${this.esc(r.RCNumber)}"></label><label>Insurance number<input name="InsuranceNumber" value="${this.esc(r.InsuranceNumber)}"></label><label class="full">KYC notes<textarea name="KYCNotes">${this.esc(r.KYCNotes)}</textarea></label><label class="full">Suspend/reject reason<textarea name="SuspendedReason">${this.esc(r.SuspendedReason)}</textarea></label>`;document.getElementById('riderModalTitle').textContent=`${r.RiderName} · ${r.VehicleNumber||r.VehicleType}`},
  async saveRider(){const f=new FormData(document.getElementById('riderForm')),data=Object.fromEntries(f.entries()),r=await DesiMallAPI.updateAdminRider({...data,Token:this.token()});this.toast(r.message||'Updated');if(r.success){document.getElementById('riderModal').classList.remove('show');await this.riders()}},
  initials(n){return String(n||'U').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()},date(v){const d=new Date(v||Date.now());return isNaN(d)?'':d.toLocaleString('en-IN')}
};document.addEventListener('DOMContentLoaded',()=>AdminLive.init());
